modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${homepage}"
//#if MC >= 26.2
iconFile = "assets/mininghelmet/icon.png"
//#else
logoFile = "assets/mininghelmet/icon.png"
//#endif
authors = "${authors}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${loader_min},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_range_maven}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
